### ISSUE TITLE
Client looks at two locations at once for assets, one does not exist

### ISSUE THREAD

**Issue by AceSoren** [oldcordapp/OldCordV3#8]
Short version is above. Long version is that the client, while it loads assets correctly now, looks into two places at once, as follows:
/assets/
/clients/assets
the latter of which actually exists within the repository. Code changes should have ensured that only the latter location is searched, so this issue is to track this problem and report any resolutions.

**Comment by ohayo** [comment]
It seems it's due to the selector.css loading the fonts twice, one loading case at an incorrect location - leading to 404 not found, this issue has since been fixed in the new selector.css file which can be downloaded currently from the clients\selector folder on the repository. Make sure your browser's cache is purged.

**Comment by ohayo** [comment]
Update: It's not the selector. @AceSoren is referring to the status.discordapp.com (original) url the client cannot make a request to as it's malformed, due to the assetMiddleware not taking into account its existence.

**Comment by ohayo** [comment]
This has now been fixed.

**Comment by AceSoren** [comment]
Thanks for the help.
